version: '3'

services:
  star:
    build: .
    volumes:
      - /share/ContainerSettings/aton_data:/aton/data
    ports:
      - 8080:8080
    networks:
      - net
    restart: unless-stopped

networks:
  net:                             
    external: true           
