version: '3'

services:
  star:
    build: .
    volumes:
      - /share/ContainerSettings/Aton/data:/aton/data
      - /share/ContainerSettings/Aton/config:/aton/config
    ports:
      - 8080:8080
    networks:
      - nginx_net
    restart: unless-stopped

networks:
  nginx_net:                             
    external: true           
